FROM quay.io/lewagon/rails-base-chrome-imagemagick:dev

ENV BUNDLER_VERSION=2.1.4

COPY bashrc /root/.bashrc

RUN apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get -yq dist-upgrade && \
  DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
  libidn11-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
  truncate -s 0 /var/log/*log

# Configure bundler
ENV LANG=C.UTF-8 \
  BUNDLE_JOBS=4 \
  BUNDLE_RETRY=3

ENV PATH /app/bin:$PATH

WORKDIR /app

COPY Gemfile Gemfile.lock package.json yarn.lock ./

RUN gem install bundler:$BUNDLER_VERSION && \
    bundle install

RUN yarn install

COPY . ./
