apiVersion: v1
kind: ConfigMap
metadata:
  name: common-env
  annotations:
    helm.sh/hook: pre-upgrade, pre-install
    helm.sh/hook-weight: "-1"
data:
  DATABASE_URL: "postgresql://{{ .Values.database.username }}:{{ .Values.database.password }}@{{ .Values.database.url }}:5432/okteto"
  REDIS_URL: redis://redis:6379/
