apiVersion: batch/v1
kind: Job
metadata:
  name: db-prepare
  annotations:
    helm.sh/hook: pre-upgrade, pre-install
spec:
  activeDeadlineSeconds: 180
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db-prepare
        image: {{ .Values.image }}
        command:
          - bundle
          - exec
          - rails
          - db:prepare
        envFrom:
        - configMapRef:
            name: common-env
