apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
spec:
  replicas: {{ .Values.sidekiq.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: sidekiq
  template:
    metadata:
      labels:
        app.kubernetes.io/component: sidekiq
    spec:
      containers:
        - name: sidekiq
          image: "{{ .Values.image }}"
          ports:
            - name: sidekiqalive
              containerPort: 7433
          command:
            - bundle
            - exec
            - sidekiq
          args:
            - "-C"
            - "config/sidekiq.yml"
          livenessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 30 # app specific. Time your sidekiq takes to start processing.
          envFrom:
          - configMapRef:
              name: common-env
