apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: {{ .Values.rails.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: chat
          image: "{{ .Values.image }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          command:
            - rails
          args:
            - "server"
            - "-b"
            - "0.0.0.0"
          envFrom:
          - configMapRef:
              name: common-env
          resources:
            limits:
              cpu: 1
              memory: 2Gi